### ISSUE TITLE
Trying to run youbot_simulation on ROS Hydro

### ISSUE THREAD

**Issue by Jabro** [a2s-institute/youbot_simulation#1]
Hello,

I'm trying to simulate a youBot under ROS Hydro. I tried your package as it has also been forked by the official youbot github account.

Unfortunately there is no documentation available here or on the ROS wiki and I'm not getting it to run right away.

Could you provide some information how to run the simulation?

I tried running 
roslaunch youbot_gazebo_control joint_state_controller.launch
and then roslaunch youbot_gazebo_worlds tower_of_hanoi.launch 

I also tried
roslaunch youbot_gazebo_robot youbot.launch
and then roslaunch youbot_gazebo_worlds tower_of_hanoi.launch 

Unfortunately both times the nodes crashed and gazebo was not started.

Best Regards,
Jabro

**Comment by Jabro** [comment]
Hello,

it was an issue on my side. Somehow there were problems with the graphics card (an ATI/AMD), which I solved by installing the proprietary fglrx driver.

Anyhow a bit documentation won't hurt. So far I was not able to move the arm. The base is moving correctly though. I will have a look at it and post the solution here as soon as I have found one.

Please provide some help if you have any idea what the problem could be.

**Comment by frederikhegger** [comment]
Hi Jabro,
nice to hear that it is working fine for you now. We will add a bit of documentation soon to the readme file.

The arm you can move with the trajectory action interface. There should be the action "/arm_1/arm_controller/follow_joint_trajectory" available.

Best regards,
Frederik
