### ISSUE TITLE
Unable to run on ROS Melodic

### ISSUE THREAD

**Issue by LeeAClift** [a2s-institute/youbot_simulation#17]
Hi,

I have been trying to get the youbot simulation working on Melodic for a few days now, will little avail.

I have the youbot_description, youbot_manipulation & youbot_simulation packages all in my catkin_ws, and they all built successfully (in this case, using the main branch for simulation).

Upon running `roslaunch youbot_gazebo_robot youbot.launch`

I get the following errors, and then Gazebo never launches. 

`[INFO] [1633618496.369193, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
`

`[gazebo-1] process has died [pid 31650, exit code 255, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode worlds/empty.world __name:=gazebo __log:=/home/lee/.ros/log/18e00a7a-2777-11ec-993e-0c9d92c25afd/gazebo-1.log].
`

`[WARN] [1633618526.652926, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
`
I have ensured that all packages and dependencies are installed, but I'm unsure how to fix this.

Any help would be very much appreciated.

Kindest Regards,
Lee

**Comment by sthoduka** [comment]
Hi Lee,

do you have `ros-melodic-gazebo-ros-control` installed? I do not see it listed in the dependencies, but I think it is required.

**Comment by LeeAClift** [comment]
Hi,

Thank you for your quick reply.

Upon rebooting and rerunning the code, it seems the first time the code is run (or Gazebo is opened), these errors don't appear. I'm assuming this is to do with Gazebo not properly finishing all of its processes. 

At this point, Gazebo still failed to boot until I rewrote the opening part of the launch file to directly open `(find gazebo_ros)/launch/empty_world.launch` instead of using the baked-in launch files. I now have Gazebo open, and the robot spawned.

Thanks for being available to help; I appreciate the availability and apologies for opening an issue over it.
